// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmhmqjahtqjfifiopqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtaG1xamFodHFqZmlmaW9wcWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NDU5NjQsImV4cCI6MjA1NTAyMTk2NH0.jf3z_JnY0QR5nX5820tXw43vB3enw9P4HDn4ywI6sRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);